-- D. JOINs (Q61–Q80)

-- Q61. List orders with customer names.
SELECT o.order_id, c.first_name, c.last_name
	FROM orders o
JOIN customers c 
ON o.customer_id = c.customer_id;

-- Q62. Show pizzas ordered with order_id.
SELECT oi.order_id, p.pizza_name
	FROM order_items oi
JOIN pizzas p 
ON oi.pizza_id = p.pizza_id;

-- Q63. Show order details with pizza_name, quantity.
SELECT p.pizza_name, oi.quantity
	FROM pizzas p
JOIN order_items oi 
ON p.pizza_id = oi.pizza_id;

-- Q64. Get customer names with their order_id.
SELECT c.first_name, c.last_name, o.order_id
	FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id;

-- Q65. Show all orders with customer city.
SELECT o.order_id, c.city 
	FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id;

-- Q66. List each pizza ordered with customer who ordered it.
SELECT 
    CONCAT(c.first_name, ' ', c.last_name) AS Cust_name,
    p.pizza_name,
    oi.quantity
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN pizzas p 
    ON oi.pizza_id = p.pizza_id;

-- Q67. Find total pizzas ordered by each customer.
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS Cust_name,
    COUNT(o.order_id) AS total_orders
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name;

-- Q68. Find total spent by each customer.
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS Cust_name,
    SUM(o.total_amount) AS Total_Spend
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name;

-- Q69. Show pizza_name with order_date.
SELECT 
    p.pizza_name,
    o.order_date
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN pizzas p
    ON oi.pizza_id = p.pizza_id;

-- Q70. List customers and their pizzas.
SELECT 
    CONCAT(c.first_name, ' ', c.last_name) AS Cust_name,
    p.pizza_name
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN pizzas p 
    ON oi.pizza_id = p.pizza_id;

-- Q71. Show each order with total pizzas ordered.
SELECT o.order_id, 
       SUM(oi.quantity) AS TotalPizza
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY o.order_id;

-- Q72. Get order_id with total cost from pizzas (price*quantity).
SELECT 
    oi.order_id,
    SUM(oi.quantity * p.price) AS TotalCost
FROM order_items oi
JOIN pizzas p 
    ON oi.pizza_id = p.pizza_id
GROUP BY oi.order_id;

-- Q73. Show pizza categories ordered by each customer.
SELECT 
    CONCAT(c.first_name,' ',c.last_name) AS Cust_Name,
    p.category
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN pizzas p 
    ON oi.pizza_id = p.pizza_id;

-- Q74. Find customers who ordered Margherita.
SELECT 
    CONCAT(c.first_name,' ',c.last_name) AS Cust_Name, 
    p.pizza_name
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON oi.order_id = o.order_id
JOIN pizzas p 
    ON p.pizza_id = oi.pizza_id
WHERE p.pizza_name = 'Margherita';

-- Q75. Show customers who ordered Non-Veg pizzas.
SELECT DISTINCT
    CONCAT(c.first_name,' ',c.last_name) AS Cust_Name,
    p.pizza_name
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON oi.order_id = o.order_id
JOIN pizzas p 
    ON p.pizza_id = oi.pizza_id
WHERE p.category = 'Non-Veg';

-- Q76. Get pizza_name and customer_name in same query.
SELECT p.pizza_name, 
       CONCAT(c.first_name,' ',c.last_name) AS Cust_Name
FROM pizzas p
JOIN order_items oi
    ON p.pizza_id = oi.pizza_id
JOIN orders o
    ON o.order_id = oi.order_id
JOIN customers c
    ON c.customer_id = o.customer_id;

-- Q77. Find total revenue generated by each pizza.
SELECT 
    p.pizza_name, 
    SUM(p.price * oi.quantity) AS TotalRevenue
FROM pizzas p
JOIN order_items oi
    ON p.pizza_id = oi.pizza_id
GROUP BY p.pizza_name
ORDER BY TotalRevenue DESC;

-- Q78. Show which pizzas were ordered in order 102.
SELECT 
    p.pizza_name
FROM pizzas p
JOIN order_items oi 
    ON p.pizza_id = oi.pizza_id
JOIN orders o 
    ON o.order_id = oi.order_id
WHERE o.order_id = 102;

-- Q79. List orders where quantity > 1.
SELECT 
    o.order_id, 
    oi.quantity
FROM orders o
JOIN order_items oi 
    ON o.order_id = oi.order_id
WHERE oi.quantity > 1;

-- Q80. Find customer who ordered Chicken Delight.
SELECT 
    CONCAT(c.first_name, ' ', c.last_name) AS Cust_Name, 
    p.pizza_name
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN pizzas p
    ON p.pizza_id = oi.pizza_id
WHERE p.pizza_name = 'Chicken Delight';

