-- D. JOINs (Q61–Q80)


-- Q61. List orders with customer names.
SELECT o.order_id, c.first_name, c.last_name
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id;

-- Q62. Show pizzas ordered with order_id.
SELECT oi.order_id, p.pizza_name
FROM order_items oi
JOIN pizzas p ON oi.pizza_id = p.pizza_id;

-- Q63. Show order details with pizza_name, quantity.
SELECT p.pizza_name, oi.quantity
FROM pizzas p
JOIN order_items oi ON p.pizza_id = oi.pizza_id;

-- Q64. Get customer names with their order_id.
SELECT c.first_name, c.last_name, o.order_id
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id;

-- Q65. Show all orders with customer city.
SELECT

-- Q66. List each pizza ordered with customer who ordered it.

-- Q67. Find total pizzas ordered by each customer.

-- Q68. Find total spent by each customer.

-- Q69. Show pizza_name with order_date.

-- Q70. List customers and their pizzas.

-- Q71. Show each order with total pizzas ordered.

-- Q72. Get order_id with total cost from pizzas (price*quantity).

-- Q73. Show pizza categories ordered by each customer.

-- Q74. Find customers who ordered Margherita.

-- Q75. Show customers who ordered Non-Veg pizzas.

-- Q76. Get pizza_name and customer_name in same query.

-- Q77. Find total revenue generated by each pizza.

-- Q78. Show which pizzas were ordered in order 102.

-- Q79. List orders where quantity > 1.

-- Q80. Find customer who ordered Chicken Delight.
